jobs:
  include:
    - language: php
      php: '7.2'
      install: composer install
    - language: php
      php: '7.3'
      install: composer install
    - language: php
      php: '7.4'
      install: composer install
    - language: node_js
      node_js: '10'
    - language: node_js
      node_js: '12'
    - language: node_js
      node_js: '13'
    - language: python
      node_js: '3.5'
    - language: python
      node_js: '3.6'
    - language: python
      node_js: '3.7'
    - language: python
      node_js: '3.8'
